# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

In [153]:
!pip install numpy --upgrade

  Using cached numpy-1.22.2-cp39-cp39-macosx_10_14_x86_64.whl (17.6 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
tensorflow 2.5.0 requires numpy~=1.19.2, but you have numpy 1.22.2 which is incompatible.
numba 0.54.1 requires numpy<1.21,>=1.17, but you have numpy 1.22.2 which is incompatible.
bokeh 2.4.1 requires typing-extensions>=3.10.0, but you have typing-extensions 3.7.4.3 which is incompatible.


#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
np.__version__

'1.19.5'

In [4]:
np.show_config

<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [7]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [9]:
print(a.size)
print(a.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [11]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [13]:
b=np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [14]:
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [17]:
c=np.arange(9)
c.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [18]:
nz=np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [21]:
i=np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [26]:
r=np.random.random((3,3,3))
r

array([[[0.27607918, 0.25910155, 0.9866641 ],
        [0.9516548 , 0.4232515 , 0.47975729],
        [0.60194205, 0.71542341, 0.30285513]],

       [[0.01517222, 0.56182592, 0.142934  ],
        [0.24774442, 0.6110227 , 0.34551681],
        [0.78626498, 0.39520242, 0.26634262]],

       [[0.22526939, 0.15356635, 0.15032549],
        [0.16742065, 0.67830224, 0.62227269],
        [0.10770461, 0.57523007, 0.42238779]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [27]:
ran=np.random.random((10,10))
print(ran.min())
print(ran.max())

0.009293650944925291
0.9989304264963946


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [34]:
mea=np.random.random(30)
mea.mean()

0.45188536568650217

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [35]:
d = np.ones((10,10))
d[1:-1,1:-1] = 0
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [37]:
e = np.ones((8,8))
e = np.pad(e, pad_width=1, mode='constant', constant_values=0)
e

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [38]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [39]:
p= np.diag(1+np.arange(4),k=-1)
p

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [42]:
eight = np.zeros((8,8),dtype=int)
eight[1::2,::2] = 1
eight[::2,1::2] = 1
eight

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [43]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [44]:
t = np.tile(np.array([[0,1],[1,0]]),(4,4))
t

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [45]:
n = np.random.random((5,5))
n = (n - np.mean (n)) / (np.std (n))
n

array([[-0.04981683,  0.4669979 , -0.53774192, -0.35566711,  0.35402101],
       [ 1.23022576, -0.4180119 ,  1.17265139,  1.20321318,  0.33952724],
       [ 0.63432116, -1.68675146, -1.16327893, -0.08841746, -1.96115547],
       [ 1.13680866,  0.74786745,  0.61614497,  0.37130782, -2.16225245],
       [-0.81608869,  0.14308886,  0.93721896, -1.18440755,  1.07019542]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [47]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [48]:
mul = np.dot(np.ones((5,3)), np.ones((3,2)))
mul

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [49]:
d = np.arange(11)
d[(3 < d) & (d < 8)] *= -1
d

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [50]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [58]:
Z=2
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
All of the expressions are valid

False

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [59]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/35/7tt4x76j60925c0qhwsl5cjw0000gn/T/ipykernel_20773/548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
/var/folders/35/7tt4x76j60925c0qhwsl5cjw0000gn/T/ipykernel_20773/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [61]:
f = np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(f)), f)

array([-2., -4.,  1., -6.,  3.,  7., -1., -8.,  3.,  7.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [64]:
a= np.random.randint(0,10,10)
b= np.random.randint(0,10,10)
print(a)
print(b)
print(np.intersect1d(a,b))

[2 6 4 0 8 7 2 9 9 2]
[7 9 8 0 6 8 4 3 5 0]
[0 4 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [65]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)

with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [66]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/35/7tt4x76j60925c0qhwsl5cjw0000gn/T/ipykernel_20773/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [68]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,today,tomorrow)

2022-02-19 2022-02-20 2022-02-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [69]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [70]:
a = np.ones(3)*1
b = np.ones(3)*2
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [71]:
r = np.random.uniform(0,10,10)

print(r - r%1)
print(r // 1)
print(np.floor(r))
print(r.astype(int))
print(np.trunc(r))

[8. 5. 9. 7. 1. 8. 1. 3. 7. 3.]
[8. 5. 9. 7. 1. 8. 1. 3. 7. 3.]
[8. 5. 9. 7. 1. 8. 1. 3. 7. 3.]
[8 5 9 7 1 8 1 3 7 3]
[8. 5. 9. 7. 1. 8. 1. 3. 7. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [72]:
five = np.tile(np.arange(0, 5), (5,1))
five

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [74]:
def generator():
    for a in range(10):
        yield a
b = np.fromiter(generator(),dtype=float,count=-1)
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [76]:
a = np.linspace(0,1,11,endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [78]:
a = np.random.random(10)
a.sort()
a

array([0.02608511, 0.08299667, 0.11031022, 0.20962955, 0.22074691,
       0.26390923, 0.48263845, 0.55281621, 0.71654136, 0.96842783])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [80]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [82]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
equal

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [83]:
a = np.zeros(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [84]:
a = np.random.random((10,2))
b,c = a[:,0], a[:,1]
r = np.sqrt(b**2+c**2)
t = np.arctan2(c,b)
print(r)
print(t)

[0.65026195 0.78192126 0.78564238 1.0585577  0.96910236 0.80778797
 0.63188194 0.43151132 0.58366795 0.24101857]
[0.4916635  0.94169549 0.16348567 0.80412848 1.46093127 1.47699327
 0.78069051 0.66514369 0.88275632 1.38007589]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [87]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.16274112, 0.19719691, 0.05746641, 0.04193199, 0.37760076,
       0.44266101, 0.17769101, 0.16236275, 0.        , 0.93573302])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [89]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
a

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [93]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
np.linalg.det(c)

3638.1636371179666

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [94]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [96]:
np.set_printoptions(threshold=float("inf"))
a = np.zeros((40,40))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [98]:
a= np.arange(100)
b = np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
a[index]

16

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [99]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
Z

/var/folders/35/7tt4x76j60925c0qhwsl5cjw0000gn/T/ipykernel_20773/1081022671.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [101]:
a = np.random.random((10,2))
b,c = np.atleast_2d(a[:,0], a[:,1])
d= np.sqrt( (b-b.T)**2 + (c-c.T)**2)
d

array([[0.        , 0.47128888, 0.22449687, 0.98284406, 0.84443359,
        0.86487685, 0.32266898, 0.6833228 , 1.2528713 , 0.83321107],
       [0.47128888, 0.        , 0.34138163, 0.55115581, 0.70740208,
        0.6845267 , 0.17410154, 0.61817298, 0.80488396, 0.53161332],
       [0.22449687, 0.34138163, 0.        , 0.89149021, 0.90854029,
        0.91060417, 0.27060913, 0.76932593, 1.14577813, 0.61057558],
       [0.98284406, 0.55115581, 0.89149021, 0.        , 0.63186994,
        0.56231428, 0.66133384, 0.68561708, 0.27605363, 0.82878574],
       [0.84443359, 0.70740208, 0.90854029, 0.63186994, 0.        ,
        0.07530603, 0.64972374, 0.17250342, 0.85039396, 1.21789104],
       [0.86487685, 0.6845267 , 0.91060417, 0.56231428, 0.07530603,
        0.        , 0.64529002, 0.22184038, 0.77588664, 1.18229312],
       [0.32266898, 0.17410154, 0.27060913, 0.66133384, 0.64972374,
        0.64529002, 0.        , 0.52636381, 0.93027116, 0.67048307],
       [0.6833228 , 0.61817298, 0.7693259

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [102]:
x = (np.random.rand(10)*100).astype(np.float32)
y = x.view(np.int32)
y[:] = x
y

array([96, 29, 27, 87, 49, 33, 63,  8, 89, 35], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [103]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
a= np.genfromtxt(s, delimiter=",", dtype=np.int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [106]:
a = np.arange(6).reshape(3,2)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [108]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
g

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [109]:
n = 10
p = 3
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False),1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [111]:
a = np.random.rand(3, 10)
b = a - a.mean(axis=1, keepdims=True)
b

array([[-0.06307979,  0.03696314, -0.51343082,  0.20587693, -0.11197667,
         0.37684277,  0.10850479, -0.47940413,  0.13495053,  0.30475325],
       [ 0.37923142, -0.01828656, -0.51610703, -0.36270411, -0.16625062,
        -0.39955767,  0.37119704,  0.05654602,  0.299173  ,  0.35675851],
       [ 0.05905278, -0.35785369, -0.2478178 , -0.01352674,  0.22862074,
        -0.07025182,  0.37215739, -0.49684705,  0.20319773,  0.32326846]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [113]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[7 2 4]
 [2 2 1]
 [3 5 3]]
[[7 2 4]
 [2 2 1]
 [3 5 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [114]:
a= np.random.randint(0,4,(5,10))
print((~a.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [128]:
A= np.random.uniform(0,1,10)
a = 0.5
b = A.flat[np.abs(A - a).argmin()]
print(b)

0.494337920636011


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [129]:
a= np.arange(3).reshape(3,1)
b= np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [135]:
class Name(np.ndarray):
    def __new__(classs, array, name="no name"):
        objectt = np.asarray(array).view(classs)
        objectt.name = name
        return objectt
    def __array_finalize__(self, objectt):
        if objectt is None: return
        self.info = getattr(objectt, 'name', "no name")
a = Name(np.arange(10), "range_10")
print (a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [136]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
a

array([3., 3., 4., 2., 2., 3., 3., 3., 4., 3.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [137]:
a = [1,2,3,4,5,6]
b = [1,3,9,3,4,1]
c = np.bincount(b,a)
c

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [138]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
n

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [141]:
A = np.random.randint(0,10,(3,4,3,4))
sum1 = A.sum(axis=(-2,-1))
print(sum1)


[[47 72 58 59]
 [51 64 50 48]
 [49 37 59 42]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [142]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.439424
1    0.422531
2    0.599502
3    0.574391
4    0.529461
5    0.438985
6    0.509785
7    0.706098
8    0.554004
9    0.553765
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [143]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.sum(A * B.T, axis=1)

array([1.17012974, 0.88899832, 0.35523104, 0.75033939, 1.14271431])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [144]:
a = np.array([1,2,3,4,5])
aa = 3
a0 = np.zeros(len(a) + (len(a)-1)*(aa))
a0[::aa+1] = a
print(a0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [145]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [148]:
a = np.arange(25).reshape(5,5)
print(a)
a[[3,4]] = a[[4,3]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [15 16 17 18 19]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [149]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 8, 34) ( 8, 36) (11, 27) (11, 29) (11, 47) (11, 76) (15, 70) (15, 73)
 (19, 31) (19, 33) (20, 53) (20, 91) (21, 85) (21, 88) (24, 52) (24, 83)
 (27, 76) (29, 47) (31, 33) (34, 36) (46, 49) (46, 66) (49, 66) (52, 83)
 (53, 91) (70, 73) (70, 88) (70, 98) (85, 88) (88, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [150]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [154]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


ImportError: cannot import name 'sliding_window_view' from 'numpy.lib.stride_tricks' (/Users/pavitrank/opt/anaconda3/lib/python3.9/site-packages/numpy/lib/stride_tricks.py)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [159]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [162]:
a = np.random.uniform(-1.0,1.0,100)
print(np.negative(a, out=a))

b = np.random.randint(0,2,100)
print(np.logical_not(b, out=b))

[-2.97693582e-01  4.67085624e-01 -3.37608828e-01 -7.63793084e-01
 -1.61130536e-01 -1.05410925e-01  5.03587058e-01  7.58283613e-01
  9.79301636e-01 -7.75986347e-01 -8.73363317e-01  4.47554207e-01
  5.41479403e-01  4.47231474e-01  4.41058521e-01  1.24286994e-02
  3.02240395e-01  9.24060599e-01 -1.84758712e-01 -8.51426573e-01
  2.76400797e-02 -7.28650408e-01 -2.58117361e-01 -4.60381114e-01
 -9.52867349e-01  7.70553855e-01  1.42459644e-01  8.51451602e-01
 -3.79120262e-01 -2.42919467e-01 -7.32629940e-01 -6.61573578e-01
 -5.49137990e-01 -5.36238210e-01 -4.97516736e-01  3.51787363e-01
 -1.13879965e-01  9.14429669e-01 -5.52238365e-01  8.68181839e-01
  1.27495354e-01 -9.06778444e-01 -9.31334723e-02 -9.90363460e-01
 -7.00486257e-01  8.47023800e-01  3.38389052e-01 -5.26879890e-01
  3.83307062e-01  1.53200509e-01  1.51053851e-01  6.28201563e-01
 -5.23902672e-01 -8.14188429e-01 -9.75518714e-01  7.05089798e-01
 -6.38931632e-01  3.59617295e-01  1.07779590e-01  8.75886863e-01
  9.06420476e-02 -4.24386

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [163]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[10.31930929 10.08821387  2.14539749  1.04780477 11.17097236  3.33631099
  4.59435948 11.47476135  6.99483523  2.4896664 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [164]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[12.30342831 15.26333144 17.88161401  7.15663901  6.77889715  1.82181787
   5.19623419  0.66405556 13.10543218 12.96282672]
 [ 8.05601839 13.71374108 17.70721288  2.36580526 10.66347281  5.2989643
   0.57429492  4.83476429  8.15080813  9.50794852]
 [ 5.71727187  9.22494668 12.74782623  5.76472648  6.36089765  0.74269342
   4.19385149  3.60834705  6.95544455  6.30024424]
 [ 1.74449327  7.66118822 13.99123664  4.57547782 15.23795219  8.91333838
   5.89031621 14.62424895  2.23719279  0.64675553]
 [ 2.80677849  0.06062856  1.62723192 16.13752671  5.54822149 11.51201083
  14.97110478  2.24685729  7.02757878  0.98007926]
 [ 3.82474234 10.20599825 14.90613248  0.85449339 11.05336836  5.26712057
   0.69981031  8.01442677  4.04306978  5.36100238]
 [ 7.88503261 14.79148525 19.22536507  0.27974333 12.83994977  7.46824497
   1.54499557  6.39027413  7.47066004  9.77823115]
 [ 5.97503463 13.53858419 18.40306721  0.95125452 13.60152482  8.04211532
   2.68052137  8.21230979  5.47708618  8.02496412]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [165]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 1 0 2 8 5 4 7 1 1]
 [1 1 7 2 4 7 9 1 5 4]
 [7 3 6 1 7 1 0 9 7 3]
 [3 5 9 4 9 8 0 0 3 1]
 [1 6 9 2 5 3 7 5 3 0]
 [1 2 9 3 0 4 4 1 1 9]
 [7 2 4 2 9 1 7 9 0 8]
 [2 2 2 8 8 6 1 8 3 7]
 [9 3 3 8 6 5 1 7 0 3]
 [8 9 7 4 3 8 4 4 0 5]]
[[0 0 0 0 0]
 [0 0 1 0 2]
 [0 1 1 7 2]
 [0 7 3 6 1]
 [0 3 5 9 4]]


/var/folders/35/7tt4x76j60925c0qhwsl5cjw0000gn/T/ipykernel_20773/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [166]:
a = np.arange(1,15,dtype=np.uint32)
r = stride_tricks.as_strided(a,(11,4),(4,4))
print(r)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [167]:
a = np.random.uniform(0,1,(10,10))
b,c,d = np.linalg.svd(a) 
matrank = np.sum(c > 1e-10)
print(matrank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [169]:
a = np.random.randint(0,10,50)
print(a)
print(np.bincount(a).argmax())

[2 4 6 1 0 9 9 7 1 8 7 0 6 8 2 3 5 1 9 5 6 5 9 0 4 1 5 6 3 4 0 2 4 2 7 0 4
 9 7 7 3 5 4 6 3 0 5 9 1 7]
0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [170]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
D = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(D)

[[[[2 1 3]
   [3 2 4]
   [0 3 4]]

  [[1 3 2]
   [2 4 2]
   [3 4 1]]

  [[3 2 3]
   [4 2 4]
   [4 1 0]]

  [[2 3 0]
   [2 4 1]
   [1 0 0]]

  [[3 0 1]
   [4 1 0]
   [0 0 0]]

  [[0 1 2]
   [1 0 2]
   [0 0 4]]

  [[1 2 4]
   [0 2 4]
   [0 4 4]]

  [[2 4 3]
   [2 4 2]
   [4 4 0]]]


 [[[3 2 4]
   [0 3 4]
   [1 1 1]]

  [[2 4 2]
   [3 4 1]
   [1 1 3]]

  [[4 2 4]
   [4 1 0]
   [1 3 1]]

  [[2 4 1]
   [1 0 0]
   [3 1 2]]

  [[4 1 0]
   [0 0 0]
   [1 2 0]]

  [[1 0 2]
   [0 0 4]
   [2 0 4]]

  [[0 2 4]
   [0 4 4]
   [0 4 1]]

  [[2 4 2]
   [4 4 0]
   [4 1 4]]]


 [[[0 3 4]
   [1 1 1]
   [2 4 0]]

  [[3 4 1]
   [1 1 3]
   [4 0 3]]

  [[4 1 0]
   [1 3 1]
   [0 3 1]]

  [[1 0 0]
   [3 1 2]
   [3 1 2]]

  [[0 0 0]
   [1 2 0]
   [1 2 4]]

  [[0 0 4]
   [2 0 4]
   [2 4 2]]

  [[0 4 4]
   [0 4 1]
   [4 2 4]]

  [[4 4 0]
   [4 1 4]
   [2 4 0]]]


 [[[1 1 1]
   [2 4 0]
   [3 1 4]]

  [[1 1 3]
   [4 0 3]
   [1 4 4]]

  [[1 3 1]
   [0 3 1]
   [4 4 1]]

  [[3 1 2]
   [3 1 2]
   [4 1 1]]

  [[1 2 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [171]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 15  5 12  0]
 [15  5  7 13  7]
 [ 5  7  5 42  6]
 [12 13 42  2 10]
 [ 0  7  6 10  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [172]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [173]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [174]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [177]:
Z = np.arange(1000000)
np.random.shuffle(Z)
n = 10
print (Z[np.argpartition(-Z,n)[:n]])

[999997 999996 999992 999999 999994 999993 999998 999995 999991 999990]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [178]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [180]:
a = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
r = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(r)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [181]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

967 ms ± 2.41 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
128 ms ± 797 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
123 ms ± 958 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [182]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [183]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 1 1]
 [2 3 2]
 [2 2 0]
 [3 2 0]
 [4 4 4]
 [0 2 1]
 [3 3 4]
 [0 3 3]
 [1 2 4]
 [1 4 1]]
[[3 1 1]
 [2 3 2]
 [2 2 0]
 [3 2 0]
 [0 2 1]
 [3 3 4]
 [0 3 3]
 [1 2 4]
 [1 4 1]]
[[3 1 1]
 [2 3 2]
 [2 2 0]
 [3 2 0]
 [0 2 1]
 [3 3 4]
 [0 3 3]
 [1 2 4]
 [1 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [184]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [185]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [186]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.15757191, 0.07196261, 0.12226867, 0.02082566, 0.12039315,
        0.01096333, 0.01202775, 0.15671852, 0.03195805, 0.1377387 ],
       [0.26731853, 0.12208356, 0.20742708, 0.03533044, 0.20424528,
        0.01859913, 0.02040491, 0.26587077, 0.05421639, 0.23367177],
       [0.29130335, 0.13303736, 0.22603822, 0.03850042, 0.22257093,
        0.02026791, 0.02223572, 0.28972569, 0.05908088, 0.25463768],
       [0.10344731, 0.04724407, 0.08027043, 0.01367222, 0.07903913,
        0.00719752, 0.00789632, 0.10288705, 0.02098074, 0.09042664],
       [0.29493945, 0.13469795, 0.22885966, 0.03898099, 0.2253491 ,
        0.0205209 , 0.02251327, 0.2933421 , 0.05981834, 0.25781611],
       [0.76089062, 0.34749645, 0.59041669, 0.10056392, 0.58136007,
        0.05294023, 0.05808017, 0.75676975, 0.15432054, 0.6651191 ],
       [0.08032377, 0.03668362, 0.06232761, 0.01061608, 0.06137154,
        0.00558866, 0.00613126, 0.07988875, 0.01629092, 0.07021361],
       [0.8112557 , 0.37049803, 0.6294977

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [187]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [188]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [189]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.36146933  0.01150321]
